version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - hms-network

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=hms_terminology
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - hms-network

volumes:
  redis_data:
  postgres_data:

networks:
  hms-network:
    driver: bridge